First stage for API
ImportError: cannot import name 'app' from partially initialized module 'pisenseapp.views' (most likely due to a circular import) (D:\Git\tfe-PiSense\web\www\pisenseapp\views.py)