First try with API
This error occurs with BMP280, BME280, BME680.
Need to continue to change SDS011 sensor code also in order to send data over API when all this will be fixed.

Traceback (most recent call last):
  File "bme280/bme280sensor.py", line 121, in <module>
    post_data()
  File "bme280/bme280sensor.py", line 99, in post_data
    logger.info('Status code: %s - %s', str(r.status_code), r.json()['message'])
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 2 (char 1)